# Generated by Django 4.0.1 on 2022-02-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isbn_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='bookauthorrelation',
            table='book_author_relation',
        ),
    ]
